services:
  bitcoin:
    container_name: bitcoin
    image: flarefoundation/bitcoin:29.1
    restart: on-failure:3
    environment:
      - TZ=Europe/London
    ports:
      - ${BIND_IP}:9332:9332
    volumes:
      - bitcoin-data:/opt/bitcoin/.bitcoin/db
      - ./config/bitcoin/bitcoin.conf:/opt/bitcoin/.bitcoin/bitcoin.conf

  litecoin:
    container_name: litecoin
    image: flarefoundation/litecoin:0.21.4
    restart: on-failure:3
    environment:
      - TZ=Europe/London
    ports:
      - ${BIND_IP}:8332:8332
    volumes:
      - litecoin-data:/opt/litecoin/.litecoin/db
      - ./config/litecoin/litecoin.conf:/opt/litecoin/.litecoin/litecoin.conf

  dogecoin:
    container_name: dogecoin
    image: flarefoundation/dogecoin:1.14.9
    restart: on-failure:3
    environment:
      - TZ=Europe/London
    ports:
      - ${BIND_IP}:7332:7332
    volumes:
      - dogecoin-data:/opt/dogecoin/.dogecoin/db
      - ./config/dogecoin/dogecoin.conf:/opt/dogecoin/.dogecoin/dogecoin.conf

  rippled:
    container_name: rippled
    image: flarefoundation/rippled:2.6.1-dless
    restart: on-failure:3
    environment:
      - TZ=Europe/London
    ports:
      - ${BIND_IP}:5005:5005   # port_rpc_admin_local
      - ${BIND_IP}:6006:6006   # port_ws_admin_local
      - ${BIND_IP}:51235:51235 # port_peer
      - ${BIND_IP}:51234:51234 # port_rpc_public
      - ${BIND_IP}:51233:51233 # port_ws_public
      - ${BIND_IP}:50051:50051 # port_grpc
    volumes:
      - ripple-data:/opt/ripple/.ripple/db:rw
      - ./config/ripple/rippled.conf:/opt/ripple/.ripple/rippled.conf:ro
      - ./config/ripple/validators.txt:/opt/ripple/.ripple/validators.txt:ro

  algorand:
    container_name: algorand
    image: flarefoundation/algorand:4.2.1
    restart: on-failure:3
    ports:
      - ${BIND_IP}:6332:8080
      - ${BIND_IP}:4160:4160
      - ${BIND_IP}:9100:9100
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - TZ=Europe/London
    volumes:
      - algorand-data:/opt/algorand/.algorand
      - ./config/algorand/config.json:/opt/algorand/.algorand/config.json
      - ./config/algorand/algod.token:/opt/algorand/.algorand/algod.token

volumes:
  bitcoin-data:
  litecoin-data:
  dogecoin-data:
  ripple-data:
  algorand-data:
