services:
  bitcoin:
    image: flarefoundation/bitcoin:28.1
    restart: on-failure:3
    environment:
      - TZ=Europe/London
    ports:
      - ${BIND_IP}:9332:9332
    volumes:
      - bitcoin-data:/opt/bitcoin/.bitcoin/db
      - ./config/bitcoin/bitcoin.conf:/opt/bitcoin/.bitcoin/bitcoin.conf

  litecoin:
    image: flarefoundation/litecoin:0.21.3
    restart: on-failure:3
    environment:
      - TZ=Europe/London
    ports:
      - ${BIND_IP}:8332:8332
    volumes:
      - litecoin-data:/opt/litecoin/.litecoin/db
      - ./config/litecoin/litecoin.conf:/opt/litecoin/.litecoin/litecoin.conf

  dogecoin:
    image: flarefoundation/dogecoin:1.14.9
    restart: on-failure:3
    environment:
      - TZ=Europe/London
    ports:
      - ${BIND_IP}:7332:7332
    volumes:
      - dogecoin-data:/opt/dogecoin/.dogecoin/db
      - ./config/dogecoin/dogecoin.conf:/opt/dogecoin/.dogecoin/dogecoin.conf

  rippled:
    image: flarefoundation/rippled:2.4.0
    restart: on-failure:3
    environment:
      - TZ=Europe/London
    ports:
      - ${BIND_IP}:5005:5005   # port_rpc_admin_local
      - ${BIND_IP}:6006:6006   # port_ws_admin_local
      - ${BIND_IP}:51235:51235 # port_peer
      - ${BIND_IP}:51234:51234 # port_rpc_public
      - ${BIND_IP}:51233:51233 # port_ws_public
      - ${BIND_IP}:50051:50051 # port_grpc
    volumes:
      - ripple-data:/opt/ripple/.ripple/db
      - ./config/ripple/rippled.conf:/opt/ripple/.ripple/rippled.conf
      - ./config/ripple/validators.txt:/opt/ripple/.ripple/validators.txt

  algorand:
    image: flarefoundation/algorand:4.1.2
    ports:
      - ${BIND_IP}:6332:8080
      - ${BIND_IP}:4160:4160
      - ${BIND_IP}:9100:9100
    environment:
      - TZ=Europe/London      # IMPORTANT: set to your timezone or else DNSSEC fails
      #ALGOD_TOKEN: changeitchangeitchangeitchangeitchangeitchangeitchangeitchangeit
    volumes:
      - algorand-data:/opt/algorand/.algorand
      - ./config/algorand/config.json:/opt/algorand/.algorand/config.json
      - ./config/algorand/algod.token:/opt/algorand/.algorand/algod.token

volumes:
  bitcoin-data:
  litecoin-data:
  dogecoin-data:
  ripple-data:
  algorand-data:
