version: "3"

services:
  bitcoin:
    image: flarefoundation/bitcoin:24.0.1
    restart: on-failure:3
    environment:
      - TZ=Europe/London
    ports:
      - ${BIND_IP}:18332:18332
      - ${BIND_IP}:18333:18333
    volumes:
      - bitcoin-testnet-data:/opt/bitcoin/.bitcoin/db
      - ./config-testnet/bitcoin/bitcoin.conf:/opt/bitcoin/.bitcoin/bitcoin.conf
  
  litecoin:
    image: flarefoundation/litecoin:0.21.2.1
    restart: on-failure:3
    environment:
      - TZ=Europe/London
    ports:
      - ${BIND_IP}:19332:19332
      - ${BIND_IP}:19333:19333
    volumes:
      - litecoin-testnet-data:/opt/litecoin/.litecoin/db
      - ./config-testnet/litecoin/litecoin.conf:/opt/litecoin/.litecoin/litecoin.conf

  dogecoin:
    image: flarefoundation/dogecoin:1.14.6
    restart: on-failure:3
    environment:
      - TZ=Europe/London
    ports:
      - ${BIND_IP}:44555:44555
      - ${BIND_IP}:44556:44556
    volumes:
      - dogecoin-testnet-data:/opt/dogecoin/.dogecoin/db
      - ./config-testnet/dogecoin/dogecoin.conf:/opt/dogecoin/.dogecoin/dogecoin.conf

  rippled:
    image: flarefoundation/rippled:1.9.4
    restart: on-failure:3
    environment:
      - TZ=Europe/London
    ports:
      - ${BIND_IP}:15005:5005   # port_rpc_admin_local
      - ${BIND_IP}:16006:6006   # port_ws_admin_local
      - ${BIND_IP}:11235:51235 # port_peer
      - ${BIND_IP}:11234:51234 # port_rpc_public
      - ${BIND_IP}:11233:51233 # port_ws_public
      - ${BIND_IP}:10051:50051 # port_grpc
    volumes:
      - ripple-testnet-data:/opt/ripple/.ripple/db
      - ./config-testnet/ripple/rippled.conf:/opt/ripple/.ripple/rippled.conf
      - ./config-testnet/ripple/validators.txt:/opt/ripple/.ripple/validators.txt

  algorand:
    image: flarefoundation/algorand:3.14.2
    ports:
      - ${BIND_IP}:18080:8080
      - ${BIND_IP}:4161:4161
    environment:
      ALGOD_NETWORK: testnet
    volumes:
      - algorand-testnet-data:/opt/algorand/.algorand
      - ./config-testnet/algorand/config.json:/opt/algorand/.algorand/config.json
      - ./config-testnet/algorand/algod.token:/opt/algorand/.algorand/algod.token

volumes:
  bitcoin-testnet-data:
  litecoin-testnet-data:
  dogecoin-testnet-data:
  ripple-testnet-data:
  algorand-testnet-data:
